### ISSUE TITLE
Media in Unix

### ISSUE THREAD

**Issue by Alex-Vaiter** [sipsorcery/sipsorcery#196]
Hey. I want to use this library in my application. I work with Debian. Please tell me how to work with sound, which library I need to add. NAudio only works on Windows. All examples here do not show work in a unix system.

**Comment by sipsorcery** [comment]
PortAudio is the most likely looking option for supporting audio on Linux. It's on the roadmap to create an example for it.

**Comment by sipsorcery** [comment]
I've added an [example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/GetStartedPortAudio) that uses PortAudio and that's intended to eventually work on Linux. I cannot test it properly at the moment as I don't have a Linux machine with an audio device. If you're able to test and report back results that would be very helpful. The instructions are in the `Program.cs` file and I've put them below as well:

````
Usage on Linux:
The PortAduioSharp package DOES NOT install the required native libraries on Linux.

The approach I used to install the PortAudio library on Linux was:
- Install Microsoft's C++ pakcage manager (yes it works on Linux) from
  https://github.com/microsoft/vcpkg,
- Use vcpkg to install PortAudio: ./vcpkg install portaudio,
- Build this app using "dotnet run" in the same directory as the project file. It's
  expected to build successfully but fail at runtime with an error that it cannot
  locate the portaudio library.
- Copy the portaudio.so from <vcpkg dir>/installed/x64-linux/lib/portaudio.so to
  the bin directory, for example:
  aaron@pcdodo:~/src/sipsorcery/examples/GetStartedPortAudio/bin/Debug/netcoreapp3.1$ cp ~/src/vcpkg/installed/x64-linux/lib/libportaudio.so .
- Retry "dotnet run". Please report success or failure at https://github.com/sipsorcery/sipsorcery/issues/196.
````

My results from running with `libportaudio.so` being present are:

````
~/src/sipsorcery/examples/GetStartedPortAudio$ dotnet run
SIPSorcery Getting Started Demo
[18:07:50 INF] SIP UDP Channel created for 0.0.0.0:50863.
[18:07:50 INF] Call attempt to sip:*61@192.168.11.48 received a trying response INVITE 100 Trying.
Unhandled exception. System.ApplicationException: No audio output device available.
   at demo.PortAudioRtpSession.Start() in /home/aaron/src/sipsorcery/examples/GetStartedPortAudio/PortAudioRtpSession.cs:line 95
   at SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler(ISIPClientUserAgent uac, SIPResponse sipResponse)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
````

**Comment by Alex-Vaiter** [comment]
I have an audio output device, but I got the same result.
`SIPSorcery Getting Started Demo
[10:52:16 INF] Success in UdpRequest for 'SRV _sip._udp.sipsorcery.com.' on dns-server '192.168.0.1:53'
[10:52:16 INF] Success in UdpRequest for 'A sip.sipsorcery.com.' on dns-server '192.168.0.1:53'
[10:52:16 INF] SIP UDP Channel created for 0.0.0.0:32863.
[10:52:17 INF] Call attempt to sip:time@sipsorcery.com received a trying response INVITE 100 Trying.
[10:52:21 INF] Call attempt to sip:time@sipsorcery.com received a ringing response INVITE 180 Ringing.
Unhandled exception. System.ApplicationException: No audio output device available.
   at demo.PortAudioRtpSession.Start() in /home/alex/vcpkg/sipsorcery/examples/GetStartedPortAudio/PortAudioRtpSession.cs:line 95
   at SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler(ISIPClientUserAgent uac, SIPResponse sipResponse)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by sipsorcery** [comment]
Ok, thanks for testng. I'll be setting up my Linux Desktop and testing further as time permits. Might be a bit of a delay on this though.

**Comment by sipsorcery** [comment]
[cscore](https://github.com/filoe/cscore) came up on another issue. I wasn't aware of this project but it seems to provide audio support on Linux. It might be a better option than PortAudio.

**Comment by sipsorcery** [comment]
#266 works with PortAudio on my Ubuntu 20.04 machine.

**Comment by sipsorcery** [comment]
Feel free to re-open if there's any further feedback.
