### ISSUE TITLE
WebRTC data channel creation generates uncaught exception on second connection

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/sipsorcery#282]
When setting up a bi-directional data channel between the `webrtccmdline` example app and Chome the first attempt works successfully but the second fails and disconnects the `SCTP` association and then generates an uncaught exception when closing.

Steps to re-produce:

Start the `webrtcmdlne` app with:

`examples\webrtccmdline> dotnet run --ws`

In Chrome open the `examples/webrtccmdline/webrtc.html` file.

Click either of the `Start Send Offer` of `Start Receive Offer`, it doesn't matter which, click `Close` and then repeat.

The second time a log message will appear on the `webrtccmdline` log stating:

`[21:59:54 DBG] SCTP disassociated.`

And then when the `Close` button is clicked the `webrtccmdline` app will crash.

````
[22:01:20 DBG] Peer connection state changed to connected.
[22:01:20 DBG] SCTP creating association is client False 5000:5000.
[22:01:20 DBG] Transport MTU is now 1371
[22:01:20 DBG] SCTP data channel stream opened for label dc1, ppid 50, stream id 0.
[22:01:20 DBG] SCTP stream opened for label dc1 and stream ID 0 (is local stream ID False).
[22:01:20 DBG] Data channel opened by remote peer, label dc1, stream ID 0.
[22:01:20 DBG] Data channel for label dc1 now open.
[22:01:20 DBG] SCTP disassociated.
[22:01:20 DBG] STUN message received from 192.168.11.50:59142, message type BindingRequest.
[22:01:21 DBG] STUN message received from 192.168.11.50:59142, message type BindingRequest.
[22:01:22 DBG] STUN message received from 192.168.11.50:59142, message type BindingRequest.
[22:01:23 DBG] STUN message received from 192.168.11.50:59142, message type BindingSuccessResponse.
[22:01:23 DBG] DTLS server received close notification: warning(1), close_notify(0).
[22:01:23 DBG] SCTP closing association as a result of DTLS transport closure.
[22:01:23 DBG] SCTP closing all streams for association.
[22:01:23 WRN] DTLS server raised unexpected alert: fatal(2), internal_error(80), .
[22:01:23 DBG] Association receive failed TlsFatalAlert Org.BouncyCastle.Crypto.Tls.TlsFatalAlert: internal_error(80)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SIPSorcery.Net.Sctp.Packet.getByteBuffer() in C:\Dev\sipsorcery\sipsorcery-core\src\net\SCTP\messages\Packet.cs:line 98
   at SIPSorcery.Net.Sctp.Association.mkPkt(Chunk[] cs) in C:\Dev\sipsorcery\sipsorcery-core\src\net\SCTP\Association.cs:line 518
   at SIPSorcery.Net.Sctp.Association.send(Chunk[] c) in C:\Dev\sipsorcery\sipsorcery-core\src\net\SCTP\Association.cs:line 361
   at SIPSorcery.Net.Sctp.Association.closeStream(SCTPStream st) in C:\Dev\sipsorcery\sipsorcery-core\src\net\SCTP\Association.cs:line 987
   at SIPSorcery.Net.Sctp.SCTPStream.close() in C:\Dev\sipsorcery\sipsorcery-core\src\net\SCTP\SCTPStream.cs:line 190
   at SIPSorcery.Net.RTCPeerSctpAssociation.Close() in C:\Dev\sipsorcery\sipsorcery-core\src\net\WebRTC\RTCPeerSctpAssociation.cs:line 94
   at SIPSorcery.Net.RTCPeerConnection.OnDtlsAlert(AlertLevelsEnum alertLevel, AlertTypesEnum alertType, String alertDescription) in C:\Dev\sipsorcery\sipsorcery-core\src\net\WebRTC\RTCPeerConnection.cs:line 1200
   at SIPSorcery.Net.DtlsSrtpTransport.<.ctor>b__30_0(AlertLevelsEnum level, AlertTypesEnum type, String description) in C:\Dev\sipsorcery\sipsorcery-core\src\net\DtlsSrtp\DtlsSrtpTransport.cs:line 88
   at SIPSorcery.Net.DtlsSrtpServer.NotifyAlertReceived(Byte alertLevel, Byte alertDescription) in C:\Dev\sipsorcery\sipsorcery-core\src\net\DtlsSrtp\DtlsSrtpServer.cs:line 500
   at Org.BouncyCastle.Crypto.Tls.DtlsRecordLayer.Receive(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in /_/crypto/src/crypto/tls/DtlsRecordLayer.cs:line 246
   at Org.BouncyCastle.Crypto.Tls.DtlsTransport.Receive(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in /_/crypto/src/crypto/tls/DtlsTransport.cs:line 30
   --- End of inner exception stack trace ---
   at Org.BouncyCastle.Crypto.Tls.DtlsTransport.Receive(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in /_/crypto/src/crypto/tls/DtlsTransport.cs:line 45
   at SIPSorcery.Net.Sctp.Association.<startRcv>b__38_0() in C:\Dev\sipsorcery\sipsorcery-core\src\net\SCTP\Association.cs:line 293
````

**Comment by sipsorcery** [comment]
Fixed.
